### ISSUE TITLE
sample/text: font change lead to assert or exception

### ISSUE THREAD

**Issue by DaMilyutin** [tyoma/agge#10]
In here (this works)
![image](https://user-images.githubusercontent.com/44639272/215293990-81ad0a85-5129-4b53-b763-066ae399dee3.png)

But changing font to ex. "Consolas" (I have it on my system) leads to this:
![image](https://user-images.githubusercontent.com/44639272/215294095-0ae8ba54-1f6b-4b11-84a8-b0eda0b4165a.png)

**Comment by DaMilyutin** [comment]
text-gdi works
![image](https://user-images.githubusercontent.com/44639272/215294324-4d4a738a-0e03-420c-a703-b1daaa71ea25.png)

**Comment by DaMilyutin** [comment]
what samples/text assertion says:
![image](https://user-images.githubusercontent.com/44639272/215294387-bc0c2ab9-e863-4c49-8b26-c9b5ade10f19.png)

**Comment by DaMilyutin** [comment]
Ops. My bad. Arial was preinstalled as the only asset. It was the intent.

**Comment by tyoma** [comment]
Hey @DaMilyutin! Right on - to see font mapping in action you may check out samples in https://github.com/tyoma/wpl - that's a MV-controls library with a freetype font loader (you'll need CMake/conan for build).
